### PR TITLE
Renaming the word "ad" from the top banner

### LINKED ISSUE #206: GopherCon banner gets blocked by many ad blockers
I have an ad blocker installed because many sites are just insanely obnoxious with their ads. The banner ad at the top of gopher academy obnoxious at all, so I don't mind seeing it and I suspect most others don't either, but it gets blocked by most ad blockers.

I suspect this happens because of the file name - `gc-banner-ad.png`. Would you be opposed to a PR changing that name if it helped with this?

### PR DESCRIPTION
**Pull request by joncalhoun**
Fixes #206

### CODE REVIEW

**Comment by joncalhoun** [comment]
My editor is setup to automatically delete extra whitespace, so the additional changes weren't intended. Sorry if that is a pain :(

**Comment by davecheney** [comment]
If this is all that is required to get around ad blockers, there's gonna be
a whole bunch of SEO's out of a job.

**Comment by joncalhoun** [comment]
Haha, I think the only thing catching it was a random regex looking for resources with "ad" in the name. The traditional filters for ad networks etc weren't triggered because the image is hosted locally. At least, in uBlock Origin that was the case.

**Comment by davecheney** [comment]
That's such weak sauce

**Pull request merged**
