### PR TITLE
Advent 2017 - Parsing with Antlr4 and Go (Dec 10th)

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by bramp** [comment]
@parrt and @pboyer you may be interested in this article going out on the 10th of December, on using Antlr4 with Go.

**Comment by parrt** [comment]
Cool. though could you use `ALL(*)` not `LL(*)` for the adaptive `LL(*)`? thanks!

**Comment by pboyer** [comment]
@bramp - So cool!

@parrt is it okay that he's using "Antlr" as opposed to "ANTLR"? You seem pretty consistent about it in the docs and books.

**Comment by parrt** [comment]
Antlr is ok though I use ANTLR :)

**Comment by parrt** [comment]
lemme know when live so i can tweet

**Comment by dgryski** [comment]
@parrt This blog post is now live.

**Comment by bramp** [comment]
At https://blog.gopheracademy.com/advent-2017/parsing-with-antlr4-and-go/

**Pull request merged**
