### PR TITLE
Advent 2015 series: Lessons in Go while Implementing SHIELD

### PR DESCRIPTION
**Pull request by qanx**
Draft for SHIELD post due 12/25.

### CODE REVIEW

**Comment by mattfarina** [comment]
I see this is marked as draft. What needs to change before you consider it ready to publish?

**Comment by qanx** [comment]
I consider it ready to publish - I just saw that other Advent PRs were submitted as drafts and thought that was the procedure :)

**Comment by qanx** [comment]
Since this is supposed to go live tomorrow and is ready, is there anything else I need to do to get this merged today?

**Comment by mattfarina** [comment]
@qanx I have everything I need. There should be no issues with going live tomorrow. Thanks for checking in.

**Comment by qanx** [comment]
Awesome, thanks :)

**Comment by mattfarina** [comment]
Thanks for the post. It is now live at https://blog.gopheracademy.com/advent-2015/shield-backup-system/

**Pull request merged**
